version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  run_VT:
    executor: machine-executor
    steps:
      - checkout
      - run: 
          environment:
            # The deployable csar file as exported from Radon-GMT
            DEPLOY_FILE: "<name_of_csar.csar>"
            # Specify the name of the container
            VT_DOCKER_NAME: "RadonVT"
            # The VT docker image published in Dockerhub
            VT_DOCKER_IMAGE: "marklawimperial/verification-tool"
            # The path to the main.cdl file inside the container
            VT_FILES_PATH: '{"path":"/tmp/main.cdl"}'
          name: Run VT  
          command: |
            echo "Pull the latest image of VT"
            docker pull ${VT_DOCKER_IMAGE}
            echo ""
            echo "Unzip the csar"
            unzip ${DEPLOY_FILE}
            echo ""
            echo "Move relevant files to temp folder."
            mkdir -p tmp/radon-vt && cp -r _definitions tmp/radon-vt/_definitions && cp radon-vt/main.cdl tmp/radon-vt
            echo ""
            echo "Run Verification Tool as Docker image and open port 5000"
            docker run --name ${VT_DOCKER_NAME} --rm -d -p 5000:5000 -v ${PWD}/tmp/radon-vt:/tmp ${VT_DOCKER_IMAGE}
            echo ""
            echo "Wait a few seconds for the container to spin up."
            sleep 5
            echo ""
            echo "Verify the model with the main.cdl restrictions. - Detect inconsistencies."
            curl -X POST -H "Content-type: application/json" http://localhost:5000/solve/ -d ${VT_FILES_PATH}
            echo ""
            echo "Correct the model to comply with the main.cdl restrictions. - Propose correction of inconsistencies."
            curl -X POST -H "Content-type: application/json" http://localhost:5000/correct/ -d ${VT_FILES_PATH}
            echo ""
            echo "Stop the container"
            docker stop ${VT_DOCKER_NAME}
            echo ""
    
workflows:
  cloudstash:
    jobs:
      - run_VT
