pipeline {
    agent any
    stages {
        
        stage('Run DPT') {
            environment {
                DEPLOY_FILE = 'cloudstash.csar'
                DPT_DOCKER_NAME = 'RadonDPT'
                GITHUB_REPO = 'your github repo containing csar'
            }
            steps {
                sh 'echo Start DPT container and perform test...'
                sh 'mkdir -p $PWD/radon-dpt && cp -r $DEPLOY_FILE $PWD/radon-dpt'
                sh 'git clone https://github.com/radon-h2020/radon-defect-prediction-cli.git'
                sh 'cd radon-defect-prediction-cli && pip3 install -r requirements.txt --user && pip3 install . --user'
                sh 'PATH="$(python3 -m site --user-base)/bin:${PATH}" && radon-defect-predictor download-model tosca github $GITHUB_REPO && radon-defect-predictor predict tosca $DEPLOY_FILE && python --version '
                sh 'cat radondp_predictions.json'
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}



