pipeline {
    agent any
    environment {
        TEMPLATE_LIBRARY_USER = credentials('template-lib-user')
        TEMPLATE_LIBRARY_PASS = credentials('template-lib-pass')
    }
    stages {
        stage('Fetch and unpack template') {
            steps {
                sh '''
                    echo $csar_reference
                    echo $csar_version
                    BEARER_TOKEN=$(curl -X POST https://template-library-radon.xlab.si/api/auth/login -H "accept: */*" -H "Content-Type: application/json" -d "{\"username\":\"$TEMPLATE_LIBRARY_USER\",\"password\":\"$TEMPLATE_LIBRARY_USER\"}" | python3 -c "import sys, json; print(json.load(sys.stdin)['token'])")
                    curl -X GET https://template-library-radon.xlab.si/api/templates/{template_name}/versions/{version}/files -H "accept: application/octet-stream" -H "Authorization: Bearer $BEARER_TOKEN" > blueprint.tosca
                '''
            }
        }
    }
}
