pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret')
    }
    stages {
        stage('Opera deploy') {
            environment {
                DEPLOY_FILE = '<name_of_tosca.tosca>'
            }
            steps {
                // install the necessary dependencies as pip packages
                // unwrap the csar and deploy the file.
                sh '''
                    pip3 install boto3 ansible opera --user
                    opera init $DEPLOY_FILE
                    opera deploy
                '''
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}


