pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret')
    }
    stages {
        stage('Opera deploy') {
            environment {
                DEPLOY_FILE = '_definitions/<file_name>.tosca'
            }
            steps {
                sh '''
                    pip3 install boto3 ansible opera --user
                    mkdir -p /tmp && cp nodetypes/radon.nodes.legacy/AwsCreateRole/files/policy/policy.json /tmp/policy.json
                    PATH="$(python3 -m site --user-base)/bin:${PATH}"
                    opera deploy $DEPLOY_FILE
                '''
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}


