version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  fetch_blueprint_from_TL:
    executor: machine-executor
    steps:
      - checkout    
      - run: 
          environment:
            # IMPORTANT: Store Template Library credentials (TEMPLATE_LIBRARY_USER and TEMPLATE_LIBRARY_PASS) as environment variables in CircleCI before running the workflow.
            # The reference name used to store a blueprint in Template Library.
            csar_reference: "<TL_blueprint_name>"
            # The version used to store a blueprint in Template Library.
            csar_version: "<TL_blueprint_version>"
          name: Fetch blueprint from TL  
          command: |
            echo ${csar_reference}
            echo ${csar_version}
            echo ""
            # Authenticate yourself using the environment variables TEMPLATE_LIBRARY_USER & TEMPLATE_LIBRARY_PASS
            BEARER_TOKEN="$(curl -X POST https://template-library-radon.xlab.si/api/auth/login -H "accept: */*" -H "Content-Type: application/json" -d "{\"username\":\"$TEMPLATE_LIBRARY_USER\",\"password\":\"$TEMPLATE_LIBRARY_PASS\"}" | python3 -c "import sys, json; print(json.load(sys.stdin)['token'])")"
            # GET command to download the blueprint from Template Library. (Assuming that the user has access to the specified blueprint)
            curl -X GET https://template-library-radon.xlab.si/api/templates/$csar_reference/versions/$csar_version/files -H "accept: application/octet-stream" -H "Authorization: Bearer $BEARER_TOKEN" --output blueprint
    
workflows:
  cloudstash:
    jobs:
      - fetch_blueprint_from_TL
