- hosts: all
  gather_facts: no
  tasks:
    - name: Lambda "{{ function_name }}" deploy
      lambda:
        name: "{{ function_name }}"
        zip_file: "{{ zip_file }}"
        runtime: python3.6
        region: "{{ aws_region }}"
        role: "{{ aws_role }}"
        handler: image_resize.lambda_handler
      register: lambda_info
    
    - name: Create function alias name
      lambda_alias:
        function_name: "{{ function_name }}"
        name: "{{ func_alias }}" 
        region: "{{ aws_region }}"
        state: present
    
    - name: "Add invocation permission of Lambda function on AWS : {{ permission_id }}"
      lambda_policy:
        function_name: "{{ function_name }}"
        statement_id: "{{ permission_id }}"
        action: lambda:InvokeFunction
        region: "{{ aws_region }}"
        alias: "{{ func_alias }}"
        principal: "s3.amazonaws.com"

    - name: Set attributes
      set_stats:
        data: 
          function_arn: "{{lambda_info.configuration.function_arn}}" 
    